# Dependabot 自动依赖更新配置
# 为 Whosee-Whois Next.js 项目优化的配置
# 文档：https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # NPM 依赖更新配置
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Asia/Shanghai"
    
    # 审查者配置
    reviewers:
      - "AsisYu"
    
    # 安全更新优先级
    target-branch: "main"
    
    # 智能分组 - 按依赖类型分组以减少 PR 数量
    groups:
      # Next.js 核心框架更新
      nextjs-core:
        patterns:
          - "next"
          - "react"
          - "react-dom"
          - "@types/react*"
          - "eslint-config-next"
        update-types:
          - "patch"
          - "minor"
      
      # UI 和样式相关依赖
      ui-dependencies:
        patterns:
          - "tailwindcss"
          - "autoprefixer"
          - "postcss"
          - "class-variance-authority"
          - "clsx"
          - "tailwind-merge"
          - "lucide-react"
          - "framer-motion"
        update-types:
          - "patch"
          - "minor"
      
      # 国际化相关
      i18n-dependencies:
        patterns:
          - "next-intl"
          - "next-themes"
        update-types:
          - "patch"
          - "minor"
      
      # 开发工具和类型定义
      dev-dependencies:
        patterns:
          - "@types/*"
          - "typescript"
          - "eslint*"
          - "@eslint/*"
          - "cross-env"
          - "@types/node"
        update-types:
          - "patch"
          - "minor"
    
    # 忽略主要版本更新（需要手动评估）
    ignore:
      # 核心框架主版本更新需要仔细测试
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tailwindcss"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
      # 忽略已知的有问题的版本
      - dependency-name: "eslint"
        versions: ["8.0.0"]
    
    # 限制打开的 PR 数量
    open-pull-requests-limit: 6
    
    # 提交消息配置
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    
    # 拉取请求标签
    labels:
      - "dependencies"
      - "dependabot"

  # GitHub Actions 更新
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "06:00"
      timezone: "Asia/Shanghai"
    
    reviewers:
      - "AsisYu"
    
    # GitHub Actions 分组
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
    
    # 忽略主要版本更新
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    
    open-pull-requests-limit: 2
    
    commit-message:
      prefix: "ci"
      include: "scope"
    
    labels:
      - "github-actions"
      - "dependabot"